# Generated by Django 6.0.1 on 2026-01-16 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('can_spell', models.BooleanField(default=False)),
                ('example_sentence', models.TextField(blank=True)),
                ('mnemonic', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_words', to='parent.assignment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
